import pycountry

def get_iso_alpha_3(nome_pais):
    """ Returns ISO Alpha-3 code for a country or territory. """

    # Manual mapping for Portuguese country names
    manual_mapping = {
        "Brasil": "BRA",
        "China": "CHN",
        "Estados Unidos": "USA",
        "Argentina": "ARG",
        "Alemanha": "DEU",
        "Países Baixos (Holanda)": "NLD",
        "Espanha": "ESP",
        "México": "MEX",
        "Rússia": "RUS",
        "Índia": "IND",
        "Chile": "CHL",
        "Japão": "JPN",
        "Itália": "ITA",
        "Coreia do Sul": "KOR",
        "França": "FRA",
        "Canadá": "CAN",
        "Singapura": "SGP",
        "Vietnã": "VNM",
        "Paraguai": "PRY",
        "Indonésia": "IDN",
        "Reino Unido": "GBR",
        "Arábia Saudita": "SAU",
        "Tailândia": "THA",
        "Malásia": "MYS",
        "Bélgica": "BEL",
        "Emirados Árabes Unidos": "ARE",
        "Colômbia": "COL",
        "Turquia": "TUR",
        "Uruguai": "URY",
        "Egito": "EGY",
        "Portugal": "PRT",
        "Taiwan (Formosa)": "TWN",
        "Suíça": "CHE",
        "Peru": "PER",
        "Argélia": "DZA",
        "Suécia": "SWE",
        "Irã": "IRN",
        "Bolívia": "BOL",
        "Marrocos": "MAR",
        "Bangladesh": "BGD",
        "Hong Kong": "HKG",
        "Filipinas": "PHL",
        "Polônia": "POL",
        "Noruega": "NOR",
        "Dinamarca": "DNK",
        "Nigéria": "NGA",
        "África do Sul": "ZAF",
        "Austrália": "AUS",
        "Omã": "OMN",
        "Iraque": "IRQ",
        "Israel": "ISR",
        "Venezuela": "VEN",
        "Angola": "AGO",
        "Irlanda": "IRL",
        "Áustria": "AUT",
        "Guiana": "GUY",
        "Barein": "BHR",
        "Catar": "QAT",
        "Finlândia": "FIN",
        "República Dominicana": "DOM",
        "Equador": "ECU",
        "Porto Rico": "PRI",
        "Coveite (Kuweit)": "KWT",
        "Panamá": "PAN",
        "Paquistão": "PAK",
        "Tcheca, República": "CZE",
        "Gabão": "GAB",
        "Hungria": "HUN",
        "Gana": "GHA",
        "Trinidad e Tobago": "TTO",
        "Costa Rica": "CRI",
        "Eslovênia": "SVN",
        "Guatemala": "GTM",
        "Líbia": "LBY",
        "Jordânia": "JOR",
        "Uzbequistão": "UZB",
        "Romênia": "ROU",
        "Bulgária": "BGR",
        "Costa do Marfim": "CIV",
        "Grécia": "GRC",
        "Eslováquia": "SVK",
        "Tunísia": "TUN",
        "Iêmen": "YEM",
        "Libéria": "LBR",
        "Líbano": "LBN",
        "Togo": "TGO",
        "Senegal": "SEN",
        "Geórgia": "GEO",
        "Islândia": "ISL",
        "Malta": "MLT",
        "Marshall, Ilhas": "MHL",
        "Camarões": "CMR",
        "Cuba": "CUB",
        "Congo, República Democrática": "COD",
        "Mauritânia": "MRT",
        "Honduras": "HND",
        "Jamaica": "JAM",
        "Congo": "COG",
        "El Salvador": "SLV",
        "Guiné": "GIN",
        "Nova Zelândia": "NZL",
        "Bahamas": "BHS",
        "Gâmbia": "GMB",
        "Somália": "SOM",
        "Cayman, Ilhas": "CYM",
        "Estônia": "EST",
        "Nicarágua": "NIC",
        "Cazaquistão": "KAZ",
        "Lituânia": "LTU",
        "Sri Lanka": "LKA",
        "Camboja": "KHM",
        "Letônia": "LVA",
        "Albânia": "ALB",
        "Ucrânia": "UKR",
        "Luxemburgo": "LUX",
        "Croácia": "HRV",
        "Quênia": "KEN",
        "Benin": "BEN",
        "Brunei": "BRN",
        "Sérvia": "SRB",
        "Haiti": "HTI",
        "Chipre": "CYP",
        "Santa Lúcia": "LCA",
        "Síria": "SYR",
        "Serra Leoa": "SLE",
        "Maurício": "MUS",
        "Suriname": "SUR",
        "Belarus": "BLR",
        "Turcomenistão": "TKM",
        "Tanzânia": "TZA",
        "Azerbaijão": "AZE",
        "Cabo Verde": "CPV",
        "Macedônia": "MKD",
        "Moçambique": "MOZ",
        "Aruba": "ABW",
        "Laos": "LAO",
        "Antígua e Barbuda": "ATG",
        "Barbados": "BRB",
        "Madagascar": "MDG",
        "Palestina": "PSE",
        "Etiópia": "ETH",
        "Mianmar": "MMR",
        "Armênia": "ARM",
        "Montenegro": "MNE",
        "Maldivas": "MDV",
        "Liechtenstein": "LIE",
        "Timor Leste": "TLS",
        "Belize": "BLZ",
        "Granada": "GRD",
        "Sudão": "SDN",
        "Burkina Faso": "BFA",
        "Bermudas": "BMU",
        "San Marino": "SMR",
        "Malawi": "MWI",
        "Comores": "COM",
        "Bósnia-Herzegovina": "BIH",
        "Seicheles": "SYC",
        "Namíbia": "NAM",
        "Zimbábue": "ZWE",
        "Uganda": "UGA",
        "Nepal": "NPL",
        "Zâmbia": "ZMB",
        "Chade": "TCD",
        "Moldávia": "MDA",
        "Papua Nova Guiné": "PNG",
        "São Tomé e Príncipe": "STP",
        "Afeganistão": "AFG",
        "Ruanda": "RWA",
        "Tadjiquistão": "TJK",
        "Níger": "NER",
        "Fiji": "FJI",
        "Botsuana": "BWA",
        "Suazilândia": "SWZ",
        "Quirguistão": "KGZ",
        "Vaticano": "VAT",
        "Eritreia": "ERI",
        "Andorra": "AND",
        "Micronésia": "FSM",
        "Salomão, Ilhas": "SLB",
        "Guiné Equatorial": "GNQ",
        "Ilha de Man": "IMN",
        "Malavi": "MWI",
        "Nova Caledônia": "NCL",
        "Polinésia Francesa": "PYF",
        "Guadalupe": "GLP",
        "São Cristóvão e Névis": "KNA",
        "Guiné-Bissau": "GNB",
        "Reunião": "REU",
        "Mongólia": "MNG",
        "Mônaco": "MCO",
        "Virgens, Ilhas (Britânicas)": "VGB",
        "Guiana Francesa": "GUF",
        "São Vicente e Granadinas": "VCT",
        "Cook, Ilhas": "COK",
        "Bonaire, Saint Eustatius e Saba": "BES",
        "Butão": "BTN",
        "República Centro-Africana": "CAF",
        "Macau": "MAC",
        "São Bartolomeu": "BLM",
        "Samoa Americana": "ASM",
        "Turcas e Caicos, Ilhas": "TCA",
        "Toquelau": "TKL",
        "Sudão do Sul": "SSD",
        "Norfolk, Ilha": "NFK",
        "Pacífico, Ilhas do (EUA)": None,  # No standard ISO code
        "Terras Austrais Francesas": "ATF",
        "Cocos (Keeling), Ilhas": "CCK",
        "Marianas do Norte, Ilhas": "MNP",
        "Antártica": "ATA",
        "Falkland (Malvinas)": "FLK",
        "Bouvet, Ilha": "BVT",
        "Geórgia do Sul e Sandwich do Sul, Ilhas": "SGS",
        "Saara Ocidental": "ESH",
        "Lesoto": "LSO",
        "Groenlândia": "GRL",
        "Svalbard e Jan Mayen": "SJM",
        "Djibuti": "DJI",
        "Faroe, Ilhas": "FRO",
        "Heard e ilhas mcdonald, Ilha": "HMD",
        "Martinica": "MTQ",
        "Sint Maarten": "SXM",
        "São Martinho, Ilha de (parte francesa)": "MAF",
        "São Pedro e Miquelon": "SPM",
        "Virgens, Ilhas (Americanas)": "VIR",
        "Wallis e Futuna, Ilhas": "WLF",
        "Aland, Ilhas": "ALA",
        "Bancos Centrais": None,  # Not a country
        "Christmas (Navidad), Ilha": "CXR",
        "Coreia do Norte": "PRK",
        "Organizações Internacionais": None,  # Not a country
        "Santa Helena": "SHN",
        "Território Britânico do Oceano Índico": "IOT",
    }

    # Return mapped values if available
    if nome_pais in manual_mapping:
        return manual_mapping[nome_pais]

    # Try looking up in pycountry (fallback)
    try:
        return pycountry.countries.lookup(nome_pais).alpha_3
    except LookupError:
        print(f"⚠️ Warning: No ISO Code for '{nome_pais}'")
        return None
